### DISCUSSION TITLE
Show your dashbaords

### DISCUSSION THREAD

**Discussion by ibz0q** [ibz0q/lovelace-bg-animation#10] [Announcements]
Showcase your dashbaords here and tell me your favourite animations, it would really help me understand your individual use cases.

Optional: A video of your setup would be **_really_** nice too (your tablet in your home etc). Don't be shy this is a place to showoff! 

I'll go first

**Configuration**
```YAML
bg-animation:
  duration: 120000 #I like things on a long cycle
  debug: true # to help me with development
  cache: false 
  gallery:
    type: local
  header:
    transparent: true
  background:
    global:
      - id: animation.15.sound # Really like the colors, slow enough where it's not distracting
      - id: animation.17.ribbons
      - id: animation.27.tron # Slow and interesting after while...
      - id: animation.53.stars # Nostalgia.. Reminds me of Windows XP days.
      - id: animation.69.bit-ocean # Don't need to explain this one xD
```
**Video**

Will post when I return home 👍 

**Setup**

My setup runs in Fully Kiosk Browser, Samsung Tab A9+. I use theme called "yourname" because of transparency of cards.

---

This plugin hasn't officially been added to HACS, it's still very unknown. It would be nice if you could share on forums, post your videos and send curious people here.

**Comment by Daemo00** [comment]
Hi there,
somehow I discovered this awesome plugin, thanks for your work and thanks to all the involved artists!

I started with the suggested configuration, then we selected our favorites from https://github.com/ibz0q/lovelace-bg-animation/blob/main/docs/EXTENDED.md and the resulting configuration is:
```yaml
bg-animation:
  duration: 60000
  gallery:
    type: local
  transparency:
    header:
      enable: true
  background:
    global:
      - id: animation.16.veil
      - id: animation.21.noise-abstraction
      - id: animation.22.cloth-ribbons
      - id: animation.26.gpu-particles
      - id: animation.27.tron
      - id: animation.31.blooming-flower
      - id: animation.32.canvas-blending-gradient-circles
      - id: animation.35.canvas-light-explosion
      - id: animation.5.plasma
      - id: animation.52.polyhedron-galaxy
      - id: animation.6.binary-spiral
      - id: animation.63.green-circuit
      - id: animation.64.howls-moving-castle
```
This **will** be tweaked in the future, but it's already awesome to see the backgrounds when casually opening HA, here a brief preview:

https://github.com/user-attachments/assets/b05be7d6-8416-4a7e-999f-85a7dd093b65

----
About the transparent cards/badges: I used a theme based on https://github.com/thomasloven/lovelace-card-mod, since I only needed the transparency it's very minimal:
```yaml
transparent:
  card-mod-theme: transparent
  card-mod-root: |
    :host {
        --card-background-color: rgb(0, 0, 0, 0.7);
    }
  modes:
    dark:
        background-color: var(--card-background-color)
    light:
        background-color: var(--card-background-color)
```
I posted about it in https://community.home-assistant.io/t/new-badges-and-card-mod-customisation/757488/81 because it took a few hours to make it work.

**Reply by ibz0q** [reply]
Super! I like the modification with Card-mod too ;)

**Comment by keithcroshaw** [comment]
This is really cool.
I wish there was one that looked like the iOS Weather app.
With live weather animations, but they're not too distracting.

**Reply by ibz0q** [reply]
if you can provide some examples, i can see to add one

**Reply by keithcroshaw** [reply]
It's a lot of work I'm sure, but here's a playlist with annoying music to demonstrate:

https://youtube.com/playlist?list=PLVEc_lDgnDxHoQMjq9siHS2PA1l2p2vmH&si=OkSpDw72VYR5B1d1

**Reply by ibz0q** [reply]
There is another discussion on a weather app type background.  

I have created something with Cursor. Please discuss and see here https://github.com/ibz0q/lovelace-bg-animation/discussions/18 

Please contribute as it seemed fairly easily to do with Cursor.

**Comment by whyisthisbroken** [comment]
I will only say thank you for this awesome background lovelace.... well done... :)

**Comment by liteglow** [comment]
I installed this, but never got it to work.

**Reply by ibz0q** [reply]
What theme are you using? Paste your configuration too and I can have a look.

**Comment by jgueydan** [comment]
Absolutely love this but am unable to get it to show on only a particular dashboard view.  This is what I put in the raw yaml (before "title"), but the animation shows up in all of the views for that dashboard:

```
bg-animation:
  duration: 30000
  cache: true
  transition:
    enable: true
    duration: 1000
  transparency:
    header:
      enable: false
  sort: random
  background:
    view:
      honeycomb-test:
        - id: animation.92.aurora-v2
        - id: animation.64.howls-moving-castle
        - id: animation.17.ribbons
```
