### ISSUE TITLE
Feature: Enable/Disable animations based on user

### ISSUE THREAD

**Issue by CSchlipp** [ibz0q/lovelace-bg-animation#17]
It would be great if I could enable/disable the background animation based on the currently active user. 
E.g. I would like to enable the animations for the user used by my wallpanel, but disable it for the personal users used in the mobile apps.

It could be similar to the `global`/`view` sections:
```
bg-animation:
  (...)
  background:
    global:
      - id: animation.50.sidelined
    view:
      lights:
        - id: animation.11.space 
    user:
      <username>:
        - id: animation.11.space
      <anotherusername>:
        enabled: false # Or just an empty section?

```
(A similar approach is used by Wallpanel: https://github.com/j-a-n/lovelace-wallpanel)

**Comment by ibz0q** [comment]
Great suggestion I will think about it a little.

**Comment by ibz0q** [comment]
```YAML

bg-animation:
 
  conditions:
    user:
      default_action: enable
    device:
      user_agent_map:
        mobile: ["Android *"]
        desktop: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) *"]
        fully_kiosk_browser: ["FullyKioskCustomUserAgent *"]

  background:
    global: 
      - id: animation.11.space
        conditions: 
          exclude_user: [user1]
          exclude_device: [mobile, fully_kiosk_browser]
          include_period:
           - start: 2010-04-16 16:00:03
             end: 2010-04-16 16:32:03

      - id: animation.65.cristal-lands
        conditions: 
          include_user: [kiosk_user]
          include_device: [fully_kiosk_browser]

      - id: animation.17.ribbons

```
Focus might be just on users and devices for now, time is difficult to work with.

**Comment by ibz0q** [comment]
This feature has been added.

I settled for this configuration:

```YAML
bg-animation:
  duration: 93000
  debug: true
  gallery:
    type: local
  cache: false
  conditions:
    regex_device_map:
      Brave:
        - .*Chrome.*
  header:
    transparent: true
  background:
    global:
      - id: animation.88.fish-tank
        conditions:
          include_devices:
            - Brave
          include_users:
            - wallpanel
      - id: animation.88.shamrocks
        conditions:
          exclude_users:
            - ibz
```

List of users: `include_users` | `exclude_users` : `array` 

Will generate a release later, potentially staggered for overlays feature
