### ISSUE TITLE
Githup page for animations error 404 not found

### ISSUE THREAD

**Issue by toben1997** [ibz0q/lovelace-bg-animation#3]
i installt the live bg animation tryd to use it and i did not wantet to work so i tryd ofline mode and download the animations and the site is ofline and there is the error 404 for the link [https://ibz0q.github.io/lovelace-bg-animation/](url)
i think thats the reason its not working in remote mode and i cant use ist in local mode because i cant donload the animations

**Comment by ibz0q** [comment]
Can you post your config ?

**Comment by Shagni** [comment]
Having similar issues here, I placed the this into the LovelaceUI. 
 ```yaml <pre> 
bg-animation:
  duration: 60000
  header:
    transparent: true
  background:
    global:
      - id: 11.space
      - id: 13.cyber-lights
      - id: 15.sound
      - id: 7.rainbowness
      - id: 27.tron      
```


Looking at Devtools in browser, I see the above change was implemented as I am getting 404 Not Found for : 
fontawesome.min.css
regular.min.css 
solid.min.css
card.css 


Request URL:
https://ibz0q.github.io/lovelace-bg-animation/src/css/card.css
Request Method:
GET
Status Code:
404 Not Found
Referrer Policy:
same-origin

**Comment by ibz0q** [comment]
I need to update the docs as the old package IDs have changed, @Shagni try this config:

```YAML
bg-animation:
  duration: 60000
  header:
    transparent: true
  background:
    global:
      - id: animation.53.stars
      - id: animation.27.tron
      - id: animation.23.ribbons-four
```
